### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by my9a9**
$ sudo apt-get install git
$ git clone https://github.com/orangepi-xunlong/OrangePi_Build.git
$ cd OrangePi_Build
$ ls
Build_OrangePi.sh lib README.md

### CODE REVIEW

**Comment by my9a9** [comment]
$ ./Build_OrangePi.sh

**Comment by my9a9** [comment]
root

**Comment by my9a9** [comment]
Orange P

**Comment by my9a9** [comment]
Orange

**Comment by orangepi-xunlong** [comment]
Sorry, I can't accept this PR

**Pull request closed without merging**
